var examples = [
{stack:'NULL', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsa_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsa_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'vm_pdfsa_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdfsa_s_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'r__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'a_fsa__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'a_fsa__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_fsa__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'p_3msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3msl_', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msl_', buffer:'p_3mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3mpn_', buffer:'p_0mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msl_', buffer:'p_0mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_0mpn_', buffer:'spsan', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsan', buffer:'n_msa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msa_', buffer:'r__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsan', buffer:'r__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'p_0mpn_', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'p_0mpn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msl_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_fpl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msl_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'vm_pdmpd_p_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdmpd_p_', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_mpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpd_', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msn_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_is__30__', buffer:'a_msa__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_msa__', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'n_msa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msa_', buffer:'n_fsd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'n_fsd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'p_3msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3msa_', buffer:'vm_pdfsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdfsn_s_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'p_3msa_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msl_', buffer:'p_3mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'p_3mpd_', buffer:'vm_is__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msl_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'a_fsn__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsn__', buffer:'sppdn', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdn', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdn', buffer:'n_mpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpd_', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdn', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'a_fsn__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fsn__', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'n_fsn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_mpa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'spsan', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsan', buffer:'n_fsa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsan', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'p_3msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3msg_', buffer:'a_msn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_msn__', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'p_3msg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msa_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'n_fsa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vo_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vo_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vo_is__30__', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_n0__00__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vo_is__30__', buffer:'vm_n0__00__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_n0__00__', buffer:'vm_n0__00__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_n0__00__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_n0__00__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vo_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'p_3fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3fsg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vc_pdmsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msn_', buffer:'vc_pdmsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vc_pdmsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_pdmsn_s_', buffer:'a_msn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_msn__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_pdmsn_s_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_mpn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpn__', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpn__', buffer:'n_mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpn_', buffer:'vm_pdmpn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdmpn_s_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_mpn_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msa_', buffer:'spsan', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsan', buffer:'n_fsa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsan', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msa_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'a_fsa__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsa__', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fsa__', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'n_fsa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'vm_pdfpd_s_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdfpd_s_', buffer:'n_fpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_fpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'spsgy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'spsgy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsgy', buffer:'n_fsg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsg_', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsgy', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsn_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'vm_pu000_0_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pu000_0_', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pu000_0_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_is__30__', buffer:'n_fsd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsd_', buffer:'spsgy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'spsgy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsgy', buffer:'n_fsg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsg_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsgy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msl_', buffer:'cs_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'cs_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cs_', buffer:'a_msn__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_msn__', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cs_', buffer:'n_msn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msn_', buffer:'n_mpl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cs_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'vm_pu000_0_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pu000_0_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'p_3fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3fsg_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_fpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpg__', buffer:'a_fpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpg__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fpg__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'a_fpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_fpg__', buffer:'n_fpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'n_fpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fpg__', buffer:'n_fpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_fpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'vm_is__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msn_', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_is__30__', buffer:'a_fpa__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpa__', buffer:'a_fpa__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpa__', buffer:'n_fpa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fpa__', buffer:'n_fpa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'n_fpa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpa_', buffer:'p_10pg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'p_10pg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_10pg_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_is__30__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'p_3fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3fpn_', buffer:'n_fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpn_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msa_', buffer:'spsan', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsan', buffer:'n_fsa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'vm_n0__00__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_n0__00__', buffer:'a_mpg__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpg__', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_n0__00__', buffer:'n_msa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msa_', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_n0__00__', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'a_fsl__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsl__', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'zc', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fsl__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'a_fsl__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_fsl__', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_n0__00__', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_n0__00__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_fsa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsan', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'vt_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'vt_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vt_ip__30__', buffer:'vm_pdmsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdmsn_s_', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'n_fpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpg_', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fpg_', buffer:'n_fpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_fpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpd_', buffer:'zd', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zd', buffer:'n_fpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpg_', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zd', buffer:'n_msa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msa_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zd', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'n_fsa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'zd', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_fpd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pdmsn_s_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vt_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vt_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vt_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vt_ip__30__', buffer:'vm_pdfsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdfsn_s_', buffer:'n_fsg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vt_ip__30__', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'a_fsn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsn__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsg_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'a_fsn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_fsn__', buffer:'n_fsn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsg_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vt_ip__30__', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vt_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_fsg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsg__', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'a_fpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsg_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msa_', buffer:'vm_pdmpg_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_pdmpg_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdmpg_p_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'a_fsg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsg__', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msn_', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsg_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msn_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsl_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msn_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zc', buffer:'vm_pu000_0_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pu000_0_', buffer:'a_mpd__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpd__', buffer:'p_3mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3mpg_', buffer:'vm_pdmpd_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpd__', buffer:'vm_pdmpd_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdmpd_p_', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpd__', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pu000_0_', buffer:'n_mpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pu000_0_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'zc', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'vm_pu000_0_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pu000_0_', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'y', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'y', buffer:'n_mdd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_mdd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mdd_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pu000_0_', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'zc', buffer:'spsay', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'spsay', buffer:'p_3msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'p_3msa_', buffer:'vm_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsay', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'y', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'y', buffer:'xf', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'xf', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'xf', buffer:'zb', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zb', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'zb', buffer:'xf', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'xf', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zc', buffer:'xn', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'xn', buffer:'zb', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'zc', buffer:'zb', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'xf', buffer:'zb', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'zb', buffer:'zb', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zb', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'zb', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_ip__30__', buffer:'vm_pdmsn_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdmsn_p_', buffer:'n_msn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_msn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_msn__', buffer:'p_3msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'p_3msn_', buffer:'vc_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'a_msn__', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vc_ip__30__', buffer:'vm_pdmsn_s_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdmsn_s_', buffer:'n_fsg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'n_fsg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'a_msn__', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_msn__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zc', buffer:'r__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_pdfsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdfsn_s_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'vc_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vc_ip__30__', buffer:'vm_pdfsn_s_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdfsn_s_', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'xn', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'xn', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pdfsn_s_', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'xn', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'xn', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pdfsn_s_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'zc', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_fsl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'a_msn__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpg_', buffer:'n_msg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'p_0fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_0fsn_', buffer:'spsan', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsn_', buffer:'spsan', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsan', buffer:'p_000a_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'p_000a_', buffer:'vc_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsan', buffer:'vc_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_fsn_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vc_ip__30__', buffer:'a_fsn__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_fsn__', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'a_mpd__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpd__', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_mpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zs', buffer:'NULL', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpg_', buffer:'n_msn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'r__', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'vm_if__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'vm_if__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_if__30__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'q_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_if__30__', buffer:'q_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'q_', buffer:'vm_pdfsl_p_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_if__30__', buffer:'vm_pdfsl_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdfsl_p_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_if__30__', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_if__30__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_if__30__', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_if__30__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_if__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_fsa__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsa__', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msa_', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msa_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'a_mpn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpn__', buffer:'n_mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'n_mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpn_', buffer:'n_fsg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_mpn_', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_mpn_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zc', buffer:'p_000n_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_000n_', buffer:'vt_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'vt_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vt_ip__30__', buffer:'vm_pdmpn_s_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdmpn_s_', buffer:'a_fsl__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vt_ip__30__', buffer:'a_fsl__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsl__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vt_ip__30__', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vt_ip__30__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'zc', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_mpn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'vm_pdfsa_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdfsa_s_', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsa_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsa_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fpl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsa_', buffer:'n_fpl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpl_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsa_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'q_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'q_', buffer:'a_fsn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsn__', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'q_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'sppdn', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'sppdn', buffer:'a_fsg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsg__', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdn', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdn', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpd_', buffer:'p_0mpn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdn', buffer:'p_0mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'p_0mpn_', buffer:'n_mpn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdn', buffer:'n_mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpn_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdn', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'spsay', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsay', buffer:'r__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'a_msa__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'spsay', buffer:'a_msa__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_msa__', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_msa__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'spsay', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'spsay', buffer:'n_fsa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsay', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'vc_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msn_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_ip__30__', buffer:'m__msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'m__msn_', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'a_mpd__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_mpd__', buffer:'p_3fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'p_3fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'m__msn_', buffer:'p_3fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'p_3fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3fsl_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vc_ip__30__', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsl_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msl_', buffer:'xn', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'xn', buffer:'xx', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msl_', buffer:'xx', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'xx', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'n_fsg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsl_', buffer:'vm_pdmpd_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'vm_pdmpd_p_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdmpd_p_', buffer:'vc_is__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'vc_is__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'xx', buffer:'vc_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msl_', buffer:'vc_is__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_is__30__', buffer:'vm_pdmpn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdmpn_s_', buffer:'n_fsd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsd_', buffer:'vm_pdfpa_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pdmpn_s_', buffer:'vm_pdfpa_p_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdfpa_p_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fpa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pdfpa_p_', buffer:'n_fpa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pdmpn_s_', buffer:'n_fpa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pdmpn_s_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_is__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msl_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'q_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'q_', buffer:'n_fpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpg_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'q_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'q_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_ip__30__', buffer:'m__msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'m__msn_', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vc_ip__30__', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'n_mpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpd_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zc', buffer:'p_000n_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_000n_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'vm_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_ip__30__', buffer:'a_mpg__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'n_msa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'zc', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_mpd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_pdmsn_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_pdmsn_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdmsn_p_', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'zc', buffer:'n_fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpn_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'n_fpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpd_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'n_mpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_pdmsn_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_pdmsn_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdmsn_p_', buffer:'xo', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'xo', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pdmsn_p_', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msl_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pdmsn_p_', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'zc', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msn_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_ip__30__', buffer:'xn', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'xn', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'zc', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'p_3msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3msn_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'spsgy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsgy', buffer:'p_3msg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'p_3msg_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsgy', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'zc', buffer:'cs_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'cs_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cs_', buffer:'p_3fpl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3fpl_', buffer:'n_fpl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cs_', buffer:'n_fpl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpl_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cs_', buffer:'vc_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vc_ip__30__', buffer:'a_fsn__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_fsn__', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vc_ip__30__', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'cc_', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpg_', buffer:'n_fsn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vc_ip__30__', buffer:'n_fsn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cs_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpn_', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fpn_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'vm_pdfpd_p_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdfpd_p_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pdfpd_p_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pdfpd_p_', buffer:'n_fpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_fpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_mpn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpn__', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'sppdy', buffer:'a_mpd__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpd__', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_mpd_', buffer:'vo_c0__00__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'vo_c0__00__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vo_c0__00__', buffer:'vc_n0__00__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vc_n0__00__', buffer:'n_fpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vo_c0__00__', buffer:'n_fpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'n_fpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpg_', buffer:'a_fsg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsg__', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fpg_', buffer:'n_fsg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fpg_', buffer:'n_msl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msl_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fpg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'n_msn_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msn_', buffer:'a_fpl__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpl__', buffer:'a_fpl__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpl__', buffer:'n_fpl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fpl__', buffer:'n_fpl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msn_', buffer:'n_fpl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'p_3fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3fsl_', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_fsl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsl_', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsl_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_msd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_mpg_', buffer:'n_msd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsl_', buffer:'n_msd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msd_', buffer:'vm_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_ip__30__', buffer:'a_fpn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_fpn__', buffer:'a_fpn__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'a_fpn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpn__', buffer:'n_msg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msg_', buffer:'n_fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fpn__', buffer:'n_fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_ip__30__', buffer:'n_fpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpn_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msd_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_fsl_', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msa_', buffer:'vm_pdmpg_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_pdmpg_p_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pdmpg_p_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msn_', buffer:'n_fpl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpl_', buffer:'vc_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msn_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_ip__30__', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_pdmsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vc_ip__30__', buffer:'vm_pdmsn_s_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_pdmsn_s_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_pu000_0_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_pu000_0_', buffer:'a_fsa__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fsa__', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_pu000_0_', buffer:'n_fsa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsa_', buffer:'spsan', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pu000_0_', buffer:'spsan', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'spsan', buffer:'n_msa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msa_', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'spsan', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_pu000_0_', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'zc', buffer:'vc_ip__30__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'r__', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_ip__30__', buffer:'a_msn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_msn__', buffer:'vm_n0__00__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'vm_n0__00__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_n0__00__', buffer:'a_mpg__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_n0__00__', buffer:'n_mpg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_n0__00__', buffer:'n_msa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msa_', buffer:'a_fpl__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpl__', buffer:'n_fpl_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msa_', buffer:'n_fpl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpl_', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msa_', buffer:'n_fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fsl_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_n0__00__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'n_mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'p_3msn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3msn_', buffer:'vm_c0__00__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vm_c0__00__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vm_c0__00__', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_c0__00__', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'vm_n0__00__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_c0__00__', buffer:'vm_n0__00__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_n0__00__', buffer:'a_mpg__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'a_mpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_mpg__', buffer:'n_msa_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vm_n0__00__', buffer:'n_msa_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_msa_', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'n_msl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_msl_', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'zc', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_msl_', buffer:'cc_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'cc_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'cc_', buffer:'p_0fsl_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_0fsl_', buffer:'sppdy', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'cc_', buffer:'sppdy', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'sppdy', buffer:'n_fsg_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsg_', buffer:'n_fpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'sppdy', buffer:'n_fpd_', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'n_fpd_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'sppdy', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'cc_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'n_msa_', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_n0__00__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_c0__00__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'NULL', buffer:'a_fpg__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'a_fpg__', buffer:'n_fpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fpg_', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'a_fpg__', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_mpg_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpg_', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'n_mpd_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_mpd_', buffer:'n_fsn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'n_fsn_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'n_mpd_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'vc_ip__30__', buffer:'a_fsn__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'a_fsn__', buffer:'zc', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zc', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'zc', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'vc_ip__30__', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'r__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'r__', buffer:'p_3mpn_', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'},
{stack:'p_3mpn_', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'r__', buffer:'vc_ip__30__', stackTopHasArc:'false', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vc_ip__30__', buffer:'vm_d0__00__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'vm_d0__00__', buffer:'r__', stackTopHasArc:'true', bufferNextHasArc:'false', move:'RIGHT ARC'},
{stack:'r__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vm_d0__00__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'vc_ip__30__', buffer:'zs', stackTopHasArc:'true', bufferNextHasArc:'false', move:'REDUCE'},
{stack:'r__', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'LEFT ARC'},
{stack:'NULL', buffer:'zs', stackTopHasArc:'false', bufferNextHasArc:'false', move:'SHIFT'}
];
examples = _(examples);
var features = ['stack','buffer','stackTopHasArc','bufferNextHasArc'];
